import { useEffect, useState } from 'react'
import { ArrowRight, Bot, Boxes, BriefcaseBusiness, Check, ClipboardCheck, Cloud, Code2, Container, GitBranch, Globe2, LockKeyhole, Mail, Menu, MessageCircle, Network, Radar, ShieldCheck, Sparkles, Terminal, X, Zap } from 'lucide-react'
import { CONTACT_FORM_ENDPOINT, CONTACT_EMAIL, WHATSAPP_MESSAGE, WHATSAPP_NUMBER } from './config/contact'
import { siteConfig } from './config/site'
import { services, projects, blogPosts } from './data/content'
import { blogs, getBlogBySlug } from './data/blogs'
import logoImage from './assets/devopsx-mark.svg'
import BlogHome from './BlogHome'
import './styles/global.css'

const stats = [{ value: '5+', label: 'Years experience' }, { value: '50+', label: 'Projects delivered' }, { value: '20+', label: 'Teams supported' }, { value: '99.9%', label: 'Reliability focus' }]
const technologies = { Cloud: ['AWS', 'Azure', 'Google Cloud'], Containers: ['Kubernetes', 'Docker', 'Helm'], 'Infrastructure as Code': ['Terraform', 'OpenTofu', 'Bicep', 'CloudFormation'], 'CI / CD': ['GitHub Actions', 'GitLab CI', 'Jenkins', 'ArgoCD', 'FluxCD'], Observability: ['Prometheus', 'Grafana', 'Loki', 'ELK', 'Dynatrace'], Security: ['GitHub Advanced Security', 'Dependabot', 'Secret Scanning'], Automation: ['Python', 'PowerShell', 'n8n', 'REST APIs'] }
const serviceIcons = [Cloud, Container, GitBranch, Code2, ShieldCheck, Radar, Globe2, Bot, BriefcaseBusiness, ClipboardCheck]
const process = [{ number: '01', title: 'Discover', text: 'Understand your infrastructure, application and business requirements.' }, { number: '02', title: 'Design', text: 'Create a practical architecture and implementation plan.' }, { number: '03', title: 'Implement', text: 'Build automation, infrastructure, CI/CD and security controls.' }, { number: '04', title: 'Optimize', text: 'Monitor, troubleshoot and continuously improve the platform.' }]

function Logo() { return <a className="logo" href="/" aria-label="DevOpsX home"><img className="logo-image" src={logoImage} alt="" /><span className="logo-wordmark">DevOps<span>X</span></span></a> }
function Button({ children, href = '#contact', secondary = false, onClick }) { return <a className={`button ${secondary ? 'button-secondary' : ''}`} href={href} onClick={onClick}>{children}<ArrowRight size={16} /></a> }
function WhatsAppButton() { const href = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(WHATSAPP_MESSAGE)}`; return <><a className="whatsapp-button" href={href} target="_blank" rel="noreferrer" aria-label="Message DevOpsX on WhatsApp" title="Message on WhatsApp"><MessageCircle size={23} /><span>WhatsApp</span></a><EmailButton /></> }
function EmailButton() { return <a className="email-button" href={`mailto:${CONTACT_EMAIL}`} aria-label="Email Abhishek Rana" title="Email Abhishek Rana"><Mail size={22} /></a> }

function BlogPostPage({ blog }) {
  if (!blog) return <div className="blog-page"><header className="editorial-header"><div className="editorial-header-inner"><Logo /></div></header><main className="blog-not-found"><span className="editorial-kicker">404 / FIELD NOTE NOT FOUND</span><h1>This article is not available.</h1><a className="editorial-primary" href="/">Back to DevOpsX <ArrowRight size={17} /></a></main></div>
  return <div className="blog-page"><header className="editorial-header"><div className="editorial-header-inner"><Logo /><a className="editorial-menu" href="/">Back to home <ArrowRight size={15} /></a></div></header><main><article className="blog-post"><div className="editorial-wrap"><a className="blog-back" href="/">← All field notes</a><span className="editorial-kicker">{blog.category} / FIELD NOTE {String(blog.id).padStart(2, '0')}</span><h1>{blog.title}</h1><p className="blog-post-lede">{blog.excerpt}</p><div className="blog-post-meta">DevOpsX Editorial <span>·</span> {blog.readTime}{blog.publishedAt && <><span>·</span> Added {blog.publishedAt}</>}</div><div className="blog-post-content">{blog.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<h2>Production checklist</h2><ul><li>Define ownership, environments and rollback paths.</li><li>Automate repeatable checks and make failures visible.</li><li>Review security, cost and operational signals before release.</li></ul>{blog.sourceUrl && <a className="editorial-primary blog-source-link" href={blog.sourceUrl} target="_blank" rel="noreferrer">Read the original article <ArrowRight size={17} /></a>}</div></div></article></main><footer className="editorial-footer"><div className="editorial-wrap editorial-footer-inner"><div><Logo /><p>Build. Automate. Secure. Scale.</p></div><a className="editorial-menu" href="/">Return to DevOpsX <ArrowRight size={15} /></a><small>© 2026 DevOpsX. Independent DevOps & cloud consulting.</small></div></footer><WhatsAppButton /></div>
}

function BlogArchivePage() {
  return <div className="blog-page"><header className="editorial-header"><div className="editorial-header-inner"><Logo /><a className="editorial-menu" href="/">Back to home <ArrowRight size={15} /></a></div></header><main><section className="editorial-section editorial-blog-archive blog-archive-page"><div className="editorial-wrap"><a className="blog-back" href="/">← Back to DevOpsX</a><span className="editorial-kicker">DEVOPSX BLOG / 100 FIELD NOTES</span><h1>Learn, build,<br /><em>operate better.</em></h1><p className="blog-archive-intro">A practical library across DevOps, DevSecOps, CI/CD automation, GitHub Actions, YAML, Helm, shell scripting, cloud and platform engineering.</p><div className="editorial-blog-grid">{blogs.map((blog) => <article className="editorial-blog-card" key={blog.slug}><span className="editorial-category">{blog.category}</span>{blog.publishedAt && <span className="editorial-new-badge">NEW · {blog.publishedAt}</span>}<h3>{blog.title}</h3><p>{blog.excerpt}</p><div><span>{blog.readTime}</span><a href={`/blog/${blog.slug}`} target="_blank" rel="noreferrer">Read article <ArrowRight size={14} /></a></div></article>)}</div></div></section></main><footer className="editorial-footer"><div className="editorial-wrap editorial-footer-inner"><div><Logo /><p>Build. Automate. Secure. Scale.</p></div><a className="editorial-menu" href="/">Return to DevOpsX <ArrowRight size={15} /></a><small>© 2026 DevOpsX. Independent DevOps & cloud consulting.</small></div></footer><WhatsAppButton /></div>
}

function Navbar() {
  const [open, setOpen] = useState(false)
  const links = [['Services', '#services'], ['Solutions', '#solutions'], ['Projects', '#projects'], ['About', '#about'], ['Blog', '#blog'], ['Contact', '#contact']]
  return <header className="navbar"><div className="nav-inner"><Logo /><nav className={open ? 'nav-links open' : 'nav-links'}>{links.map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a>)}</nav><Button href="#contact">Book a Free Consultation</Button><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu" aria-expanded={open}>{open ? <X /> : <Menu />}</button></div></header>
}

function InfrastructureVisual() { return <div className="infra-visual" aria-label="Cloud infrastructure architecture illustration" role="img"><div className="visual-grid" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="central-node"><Network size={29} /><strong>DevOpsX</strong><small>CONTROL PLANE</small></div><div className="node node-aws"><Cloud size={18} /><span>AWS</span></div><div className="node node-azure"><Boxes size={18} /><span>AZURE</span></div><div className="node node-kube"><Container size={18} /><span>K8S</span></div><div className="node node-sec"><LockKeyhole size={16} /><span>SECURITY</span></div><div className="visual-line line-a" /><div className="visual-line line-b" /><div className="visual-line line-c" /><div className="visual-caption"><span className="status-dot" />SYSTEMS ONLINE <span>·</span> 24/7 OBSERVABILITY</div></div> }

function Hero() { return <section className="hero section-pad" id="top"><div className="hero-copy"><div className="eyebrow"><span /> DEVOPS & CLOUD CONSULTING</div><div className="availability"><span /> Accepting new projects for Q4 2026</div><h1>Cloud systems that help your business move <em>faster.</em></h1><p className="hero-lede">I help growing teams design, automate and secure the infrastructure behind reliable products, without adding unnecessary complexity.</p><div className="capabilities">{['Cloud architecture', 'Automation', 'DevSecOps', 'Reliability'].map((item) => <span key={item}><Check size={14} />{item}</span>)}</div><div className="hero-actions"><Button>Book a Project Call</Button><Button secondary href="#projects">See Selected Work</Button></div><div className="credibility"><span>Remote-first</span><i /><span>Practical advice</span><i /><span>Clear handover</span></div></div><InfrastructureVisual /></section> }
function Stats() { return <section className="stats"><div className="stats-inner">{stats.map((stat) => <div className="stat" key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div></section> }

function Services() { return <section className="section-pad section" id="services"><div className="section-heading"><div><div className="eyebrow">WHAT I DO</div><h2>Practical support for<br /><em>your next move.</em></h2></div><p>From production infrastructure to career-focused technical coaching, get clear guidance that helps you move forward with confidence.</p></div><div className="service-grid">{services.map((service, index) => { const Icon = serviceIcons[index]; return <article className="service-card" key={service.title}><div className="card-icon"><Icon size={21} /></div><h3>{service.title}</h3><p>{service.description}</p><a href="#contact">Discuss this <ArrowRight size={15} /></a></article> })}</div></section> }
function Solutions() { const items = [['01', 'Reduce deployment time', 'Automate CI/CD and eliminate repetitive deployment tasks.', Zap], ['02', 'Improve reliability', 'Build resilient Kubernetes and cloud infrastructure.', ShieldCheck], ['03', 'Strengthen security', 'Integrate security into the development and deployment lifecycle.', LockKeyhole], ['04', 'Reduce cloud cost', 'Identify waste and optimize infrastructure and workloads.', Sparkles]]; return <section className="section solutions-section" id="solutions"><div className="section-pad"><div className="section-heading"><div><div className="eyebrow">OUTCOMES, NOT OUTPUT</div><h2>Solutions built around<br /><em>your problems.</em></h2></div><p>Whether you are scaling fast or untangling legacy systems, the goal is always a calmer, more capable engineering team.</p></div><div className="solution-grid">{items.map(([number, title, text, Icon]) => <article className="solution-card" key={title}><span className="solution-number">{number}</span><Icon className="solution-icon" size={22} /><h3>{title}</h3><p>{text}</p><a href="#contact">Explore solution <ArrowRight size={15} /></a></article>)}</div><div className="workflow"><span>PLAN</span><i /><span>BUILD</span><i /><span>SECURE</span><i /><span>DEPLOY</span><i /><span>OBSERVE</span><i /><span>OPTIMIZE</span></div></div></section> }
function Technologies() { return <section className="section-pad section tech-section"><div className="section-heading"><div><div className="eyebrow">THE TOOLKIT</div><h2>Tools & technologies<br /><em>I work with.</em></h2></div></div><div className="tech-grid">{Object.entries(technologies).map(([category, tools]) => <div className="tech-group" key={category}><h3>{category}</h3><div>{tools.map((tool) => <span key={tool}>{tool}</span>)}</div></div>)}</div></section> }
function Projects() { return <section className="section projects-section" id="projects"><div className="section-pad"><div className="section-heading"><div><div className="eyebrow">REPRESENTATIVE WORK</div><h2>Real projects.<br /><em>Real impact.</em></h2></div><p>Case studies and representative work. Client details are kept confidential where appropriate.</p></div><div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.title}><div className={`project-visual project-${index + 1}`}><span>{project.label}</span><div className="project-lines" /></div><div className="project-body"><span className="project-type">{project.type}</span><h3>{project.title}</h3><p>{project.description}</p><div className="tag-row">{project.technologies.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div></div></section> }
function Process() { return <section className="section-pad section process-section"><div className="section-heading"><div><div className="eyebrow">A CLEAR PATH FORWARD</div><h2>How I <em>work.</em></h2></div><p>Good infrastructure work is collaborative, documented and designed to leave your team stronger than before.</p></div><div className="process-grid">{process.map((step, index) => <div className="process-step" key={step.number}><span>{step.number}</span>{index < process.length - 1 && <i /> }<h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section> }
function About() { return <section className="section about-section" id="about"><div className="section-pad about-grid"><div><div className="eyebrow">THE PERSON BEHIND THE PLATFORM</div><h2>Infrastructure should<br />feel <em>intentional.</em></h2></div><div className="about-copy"><p className="large-copy">DevOpsX is a focused DevOps, DevSecOps and cloud infrastructure consulting practice for teams who want to move quickly without making production fragile.</p><p>My work spans cloud infrastructure, Kubernetes, security automation, CI/CD, Infrastructure as Code and observability. The approach is practical: understand the constraints, simplify the system, and automate the path forward.</p><div className="about-tags">{['Production-focused engineering', 'Automation-first approach', 'Clear documentation', 'Remote collaboration'].map((tag) => <span key={tag}><Check size={14} />{tag}</span>)}</div></div></div></section> }
function Engagement() { return <section className="section-pad section engagement-section"><div className="section-heading"><div><div className="eyebrow">WAYS TO WORK TOGETHER</div><h2>Support that fits<br /><em>the moment.</em></h2></div></div><div className="engagement-grid">{[['Project based', 'Best for migrations, automation and infrastructure implementations.'], ['Hourly consulting', 'Best for troubleshooting, architecture reviews and technical guidance.'], ['Interview & assignment coaching', 'Best for mock interviews, technical preparation and feedback on take-home work.'], ['Monthly support', 'Best for companies requiring ongoing DevOps and cloud support.']].map(([title, text], index) => <article key={title} className={index === 1 ? 'engagement-card featured' : 'engagement-card'}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><a href="#contact">Discuss your needs <ArrowRight size={15} /></a></article>)}</div></section> }
function Blog() { return <section className="section blog-section" id="blog"><div className="section-pad"><div className="section-heading"><div><div className="eyebrow">FIELD NOTES</div><h2>Useful ideas for<br /><em>reliable systems.</em></h2></div><a className="text-link" href="#blog">View all notes <ArrowRight size={15} /></a></div><div className="blog-grid">{blogPosts.slice(0, 3).map((post) => <article className="blog-card" key={post.title}><div className="blog-art"><Terminal size={26} /><span>{post.category}</span></div><div><span className="post-meta">{post.readTime} · {post.date}</span><h3>{post.title}</h3><a href="#contact">Read article <ArrowRight size={15} /></a></div></article>)}</div></div></section> }
function Contact() { const [sent, setSent] = useState(false); const handleSubmit = (event) => { if (!CONTACT_FORM_ENDPOINT) { event.preventDefault(); const formData = new FormData(event.currentTarget); const subject = encodeURIComponent(`Project inquiry from ${formData.get('name')}`); const body = encodeURIComponent(`Name: ${formData.get('name')}\nEmail: ${formData.get('email')}\nCompany: ${formData.get('company') || 'Not provided'}\nProject type: ${formData.get('projectType') || 'Not provided'}\nBudget: ${formData.get('budget') || 'Not provided'}\n\n${formData.get('message')}`); window.location.href = `mailto:${CONTACT_EMAIL}?subject=${subject}&body=${body}`; setSent(true) } }; return <section className="contact-section" id="contact"><div className="section-pad contact-grid"><div className="contact-copy"><div className="eyebrow">START A CONVERSATION</div><h2>Make your next<br /><em>deployment</em><br />the easy one.</h2><p>Share what is slowing your team down. I’ll reply with a clear next step and an honest view of how I can help.</p><div className="contact-detail"><span>Prefer email?</span><a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></div><div className="contact-promise"><Check size={16} /> Reply within one business day</div></div><form className="contact-form" action={CONTACT_FORM_ENDPOINT || undefined} method="POST" onSubmit={handleSubmit}><div className="form-intro"><span>01</span><div><strong>Tell me about the work</strong><p>No pitch deck required. A few details are enough to start.</p></div></div><div className="form-row"><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@company.com" /></label></div><div className="form-row"><label>Company<input name="company" placeholder="Company name" /></label><label>Project type<select name="projectType" defaultValue=""><option value="" disabled>Select a focus area</option>{['DevOps Consulting', 'Cloud Migration', 'Kubernetes', 'Terraform / IaC', 'CI/CD', 'DevSecOps', 'Monitoring', 'Automation', 'Other'].map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Budget range<select name="budget" defaultValue=""><option value="" disabled>Choose a range</option>{['Under $500', '$500–$1,000', '$1,000–$5,000', '$5,000+', 'Not sure'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Message<textarea required name="message" rows="4" placeholder="What would you like to improve, launch or automate?" /></label>{sent && <p className="form-success">Your email draft is ready. Send it to complete your request.</p>}<button className="button form-button" type="submit">{CONTACT_FORM_ENDPOINT ? 'Book My Consultation' : 'Send Project Brief'} <ArrowRight size={16} /></button><small className="form-note">Typically replies within one business day. No obligation.</small></form></div></section> }
function Footer() { return <footer className="footer"><div className="footer-cta"><div><div className="eyebrow"><span /> READY WHEN YOU ARE</div><h2>Make the next<br /><em>move count.</em></h2></div><Button>Book a Project Call</Button></div><div className="footer-main"><div className="footer-brand"><Logo /><p>Build. Automate. Secure. Scale.</p><span className="footer-status"><i /> Available for remote consulting worldwide.</span></div><div className="footer-links"><div><span>Explore</span><a href="#services">Services</a><a href="#projects">Projects</a><a href="#about">About</a></div><div><span>Connect</span><a href={siteConfig.social.linkedin}>LinkedIn</a><a href={siteConfig.social.github}>GitHub</a><a href={siteConfig.social.youtube}>YouTube</a></div></div></div><div className="footer-bottom"><span>© 2026 DevOpsX. All rights reserved.</span><span>Independent DevOps & cloud consulting</span></div></footer> }

function AdLanding() { return <><Navbar /><main><section className="landing-hero section-pad"><div className="eyebrow"><span /> DEVOPS & CLOUD CONSULTING</div><h1>Hire a DevOps &<br /><em>Cloud Consultant.</em></h1><p>AWS, Azure, Kubernetes, Terraform, CI/CD and DevSecOps expertise for your next project.</p><Button>Book a Free Consultation</Button></section><Services /><Technologies /><Projects /><Engagement /><Contact /></main><Footer /></> }
function EditorialHome() {
  const featured = projects.slice(0, 3)
  const resources = [
    ['Kubernetes', 'Production Kubernetes guides, platform patterns and operational checklists.'],
    ['CI/CD & GitHub', 'Practical migration notes, reusable workflows and delivery automation.'],
    ['DevSecOps', 'Security reporting, supply-chain controls and secure engineering practices.'],
    ['Cloud & FinOps', 'AWS, Azure and cost-optimization guidance for reliable platforms.'],
  ]
  return <div className="editorial-site">
    <header className="editorial-header"><div className="editorial-header-inner"><Logo /><nav className="editorial-nav"><a href="#articles">Articles</a><a href="/blog">Blog</a><a href="#resources">Resources</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="editorial-menu" href="#resources">Topics <ArrowRight size={15} /></a></div></header>
    <main>
      <section className="editorial-hero"><div className="editorial-wrap editorial-hero-grid"><div><span className="editorial-kicker">DEVOPSX / FIELD NOTES</span><h1>Become better at building <em>reliable systems.</em></h1><p>Practical guides, field notes and consulting insight for DevOps, platform engineering, cloud security and Kubernetes teams.</p><div className="editorial-actions"><a className="editorial-primary" href="#articles">Explore the articles <ArrowRight size={17} /></a><a className="editorial-secondary" href="#contact">Work with me</a></div></div><div className="editorial-hero-art"><div className="editorial-art-grid" /><strong>BUILD<br /><span>AUTOMATE</span><br />SECURE</strong><small>DEVOPSX / 2026</small></div></div></section>
      <section className="editorial-newsletter"><div className="editorial-wrap editorial-newsletter-inner"><div><span className="editorial-kicker">THE WEEKLY SIGNAL</span><h2>Useful ideas for your next deployment.</h2><p>Join engineers exploring better infrastructure, delivery and security practices.</p></div><a className="editorial-primary" href={`mailto:${CONTACT_EMAIL}?subject=Join the DevOpsX newsletter`}>Join the community <ArrowRight size={17} /></a></div></section>
      <section className="editorial-section" id="articles"><div className="editorial-wrap"><div className="editorial-section-head"><div><span className="editorial-kicker">LATEST FIELD NOTES</span><h2>Ideas worth putting<br /><em>into production.</em></h2></div><a className="editorial-text-link" href="#articles">View all articles <ArrowRight size={15} /></a></div><div className="editorial-articles">{featured.map((project, index) => <article className={index === 0 ? 'editorial-article editorial-article-featured' : 'editorial-article'} key={project.title}><div className={`editorial-article-art article-art-${index + 1}`}><span>0{index + 1}</span><div className="editorial-art-copy"><small>{project.type}</small><strong>{project.title}</strong></div><Terminal size={28} /></div><div className="editorial-article-body"><span className="editorial-category">{project.type}</span><h3>{project.title}</h3><p>{project.description}</p><a href="#contact">Read the field note <ArrowRight size={15} /></a></div></article>)}</div></div></section>
      <section className="editorial-section editorial-blog-archive" id="blog"><div className="editorial-wrap"><div className="editorial-section-head"><div><span className="editorial-kicker">DEVOPSX BLOG / 100 FIELD NOTES</span><h2>Learn, build,<br /><em>operate better.</em></h2></div><div><p>Practical reading across DevOps, DevSecOps, CI/CD automation, GitHub Actions, YAML, Helm and shell scripting.</p><a className="editorial-text-link" href="/blog">Browse all 100 articles <ArrowRight size={15} /></a></div></div><div className="editorial-blog-grid">{blogs.slice(0, 6).map((blog) => <article className="editorial-blog-card" key={blog.slug}><span className="editorial-category">{blog.category}</span>{blog.publishedAt && <span className="editorial-new-badge">NEW · {blog.publishedAt}</span>}<h3>{blog.title}</h3><p>{blog.excerpt}</p><div><span>{blog.readTime}</span><a href={`/blog/${blog.slug}`} target="_blank" rel="noreferrer">Read article <ArrowRight size={14} /></a></div></article>)}</div></div></section>
      <section className="editorial-section editorial-resources" id="resources"><div className="editorial-wrap"><div className="editorial-section-head"><div><span className="editorial-kicker">EXPLORE BY TOPIC</span><h2>Your practical<br /><em>engineering library.</em></h2></div><p>Clear starting points for the systems and workflows that matter most to modern engineering teams.</p></div><div className="editorial-resource-list">{resources.map(([title, text], index) => <a className="editorial-resource" href="#contact" key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{text}</p></div><ArrowRight size={19} /></a>)}</div></div></section>
      <section className="editorial-about" id="about"><div className="editorial-wrap editorial-about-grid"><div><span className="editorial-kicker">THE PERSON BEHIND THE PLATFORM</span><h2>Experience that helps teams move with <em>less friction.</em></h2></div><div><p>DevOpsX is an independent DevOps, DevSecOps and cloud infrastructure practice led by Abhishek Rana. I write from hands-on experience across GitHub migrations, Azure, AWS, Kubernetes, CI/CD and security automation.</p><a className="editorial-secondary" href="#contact">About DevOpsX <ArrowRight size={15} /></a></div></div></section>
      <section className="editorial-contact" id="contact"><div className="editorial-wrap editorial-contact-inner"><div><span className="editorial-kicker">HAVE A SYSTEM OR CAREER GOAL TO IMPROVE?</span><h2>Let’s make the next move <em>count.</em></h2></div><div><p>Need help with a freelance DevOps project, platform, pipeline or security program? I also support interview preparation, job searches and technical assignments.</p><a className="editorial-primary" href={`mailto:${CONTACT_EMAIL}`}>Start a conversation <ArrowRight size={17} /></a></div></div></section>
    </main>
    <footer className="editorial-footer"><div className="editorial-wrap editorial-footer-inner"><div><Logo /><p>Build. Automate. Secure. Scale.</p></div><div className="editorial-footer-links"><a href="#articles">Articles</a><a href="#resources">Resources</a><a href="#contact">Contact</a><a href={`https://wa.me/${WHATSAPP_NUMBER}`} target="_blank" rel="noreferrer">WhatsApp</a></div><small>© 2026 DevOpsX. Independent DevOps & cloud consulting.</small></div></footer><WhatsAppButton />
  </div>
}

function SimpleHome() {
  const [pipelineState, setPipelineState] = useState('active')
  useEffect(() => {
    const failTimer = window.setTimeout(() => setPipelineState(pipelineState === 'active' ? 'error' : 'active'), pipelineState === 'active' ? 120000 : 5000)
    return () => window.clearTimeout(failTimer)
  }, [pipelineState])
  const stages = pipelineState === 'error' ? [['SOURCE', 'restart'], ['VALIDATE', 'restart'], ['BUILD', 'restart'], ['SECURITY', 'restart'], ['DEPLOY', 'error']] : [['SOURCE', 'done'], ['VALIDATE', 'done'], ['BUILD', 'done'], ['SECURITY', 'done'], ['DEPLOY', 'active']]
  return <div className="simple-site"><header className="simple-header"><Logo /><span><i /> OPEN FOR COLLABORATION</span></header><main><section className="simple-dashboard"><div className="simple-profile"><div className="simple-profile-top"><img src={logoImage} alt="DevOpsX mark" /><div><span className="simple-kicker">ABHISHEK RANA / DEVOPSX</span><h1>Abhishek Rana</h1><p>Senior DevSecOps Engineer</p><small>KEEPING PLATFORMS RUNNING SINCE 2017</small></div></div><span className="simple-kicker simple-kicker-spaced">PRACTICE STATUS</span><h2>Building <em>reliable systems.</em></h2><p className="simple-lede">Cloud infrastructure, automation and security for systems that need to keep moving. Available for freelance consulting, project delivery, interview preparation and technical assignment coaching.</p><div className="simple-links"><a href={`mailto:${CONTACT_EMAIL}`}>Email <ArrowRight size={15} /></a><a href="https://www.linkedin.com/in/abhishekrana0317/" target="_blank" rel="noreferrer">LinkedIn <ArrowRight size={15} /></a></div></div><aside className={`simple-build ${pipelineState}`}><div className="simple-build-head"><span>CI/CD PIPELINE</span><strong>{pipelineState === 'error' ? 'ERROR / RETRYING' : 'DEPLOYING'}</strong></div>{stages.map(([label, status]) => <div className={`simple-build-row ${status}`} key={label}><span>{status === 'done' ? '✓' : status === 'active' ? '→' : status === 'error' ? '×' : '↻'}</span><small>{label}</small><i><b /></i></div>)}<div className="simple-build-note">{pipelineState === 'error' ? <>Deployment failed verification.<br />Restarting from source.<br /><br />Retry loop active.</> : <>Pipeline checks passed.<br />Deployment is in progress.<br /><br />Release will be available after verification.</>}</div></aside></section><section className="simple-strip"><span>AWS</span><span>AZURE</span><span>KUBERNETES</span><span>GITHUB ACTIONS</span><span>TERRAFORM</span><span>DEVSECOPS</span></section><section className="simple-contact"><span className="simple-kicker">GET IN TOUCH</span><div className="simple-links"><a href={`mailto:${CONTACT_EMAIL}`}>Email Abhishek <ArrowRight size={15} /></a><a href={`https://wa.me/${WHATSAPP_NUMBER}`} target="_blank" rel="noreferrer">WhatsApp <ArrowRight size={15} /></a></div></section></main><footer className="simple-footer"><span>Platform engineering · DevSecOps · Cloud automation</span><span>© 2026 · Hyderabad,India</span></footer><WhatsAppButton /></div>
}

function InteractiveTerminal() {
  const [open, setOpen] = useState(false)
  const [command, setCommand] = useState('')
  const [output, setOutput] = useState(['DevOpsX console ready.', 'Type help to see available commands.'])
  const runCommand = (event) => {
    event.preventDefault()
    const value = command.trim().toLowerCase()
    const responses = {
      help: 'status   skills   contact   clear',
      status: 'systems online | pipeline deploying | collaboration open',
      skills: 'aws · azure · kubernetes · github actions · terraform · devsecops',
      contact: `email ${CONTACT_EMAIL} | whatsapp +91 7674047261`,
    }
    if (value === 'clear') setOutput([])
    else if (value) setOutput((current) => [...current, `> ${command}`, responses[value] || `command not found: ${value}`])
    setCommand('')
  }
  return <div className={`interactive-terminal ${open ? 'is-open' : ''}`}><button className="terminal-toggle" onClick={() => setOpen(!open)} aria-expanded={open}><Terminal size={16} /> {open ? 'Close console' : 'Open console'}</button>{open && <div className="terminal-window"><div className="terminal-window-bar"><span><i /> <i /> <i /></span><small>devopsx@control-plane</small></div><div className="terminal-output">{output.map((line, index) => <div key={`${line}-${index}`}>{line}</div>)}</div><form onSubmit={runCommand}><span>$</span><input autoFocus value={command} onChange={(event) => setCommand(event.target.value)} placeholder="type a command" aria-label="Terminal command" /></form></div>}</div>
}

function App() { const path = window.location.pathname; const blogSlug = path.startsWith('/blog/') ? path.replace('/blog/', '').replace(/\/$/, '') : ''; if (path === '/blog' || path === '/blog/') return <BlogArchivePage />; return blogSlug ? <BlogPostPage blog={getBlogBySlug(blogSlug)} /> : <BlogHome /> }

export default App
