import { useState } from 'react'
import { ArrowRight, Bot, Boxes, BriefcaseBusiness, Check, ClipboardCheck, Cloud, Code2, Container, GitBranch, Globe2, LockKeyhole, Menu, MessageCircle, Network, Radar, ShieldCheck, Sparkles, Terminal, X, Zap } from 'lucide-react'
import { CONTACT_FORM_ENDPOINT, CONTACT_EMAIL, WHATSAPP_MESSAGE, WHATSAPP_NUMBER } from './config/contact'
import { siteConfig } from './config/site'
import { services, projects, blogPosts } from './data/content'
import logoImage from './assets/devopsx.jpeg'
import './styles/global.css'

const stats = [{ value: '5+', label: 'Years experience' }, { value: '50+', label: 'Projects delivered' }, { value: '20+', label: 'Teams supported' }, { value: '99.9%', label: 'Reliability focus' }]
const technologies = { Cloud: ['AWS', 'Azure', 'Google Cloud'], Containers: ['Kubernetes', 'Docker', 'Helm'], 'Infrastructure as Code': ['Terraform', 'OpenTofu', 'Bicep', 'CloudFormation'], 'CI / CD': ['GitHub Actions', 'GitLab CI', 'Jenkins', 'ArgoCD', 'FluxCD'], Observability: ['Prometheus', 'Grafana', 'Loki', 'ELK', 'Dynatrace'], Security: ['GitHub Advanced Security', 'Dependabot', 'Secret Scanning'], Automation: ['Python', 'PowerShell', 'n8n', 'REST APIs'] }
const serviceIcons = [Cloud, Container, GitBranch, Code2, ShieldCheck, Radar, Globe2, Bot, BriefcaseBusiness, ClipboardCheck]
const process = [{ number: '01', title: 'Discover', text: 'Understand your infrastructure, application and business requirements.' }, { number: '02', title: 'Design', text: 'Create a practical architecture and implementation plan.' }, { number: '03', title: 'Implement', text: 'Build automation, infrastructure, CI/CD and security controls.' }, { number: '04', title: 'Optimize', text: 'Monitor, troubleshoot and continuously improve the platform.' }]

function Logo() { return <a className="logo" href="#top" aria-label="DevOpsX home"><img className="logo-image" src={logoImage} alt="DevOpsX" /></a> }
function Button({ children, href = '#contact', secondary = false, onClick }) { return <a className={`button ${secondary ? 'button-secondary' : ''}`} href={href} onClick={onClick}>{children}<ArrowRight size={16} /></a> }
function WhatsAppButton() { const href = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(WHATSAPP_MESSAGE)}`; return <a className="whatsapp-button" href={href} target="_blank" rel="noreferrer" aria-label="Message DevOpsX on WhatsApp" title="Message on WhatsApp"><MessageCircle size={23} /><span>WhatsApp</span></a> }

function Navbar() {
  const [open, setOpen] = useState(false)
  const links = [['Services', '#services'], ['Solutions', '#solutions'], ['Projects', '#projects'], ['About', '#about'], ['Blog', '#blog'], ['Contact', '#contact']]
  return <header className="navbar"><div className="nav-inner"><Logo /><nav className={open ? 'nav-links open' : 'nav-links'}>{links.map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a>)}</nav><Button href="#contact">Book a Free Consultation</Button><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu" aria-expanded={open}>{open ? <X /> : <Menu />}</button></div></header>
}

function InfrastructureVisual() { return <div className="infra-visual" aria-label="Cloud infrastructure architecture illustration" role="img"><div className="visual-grid" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="central-node"><Network size={29} /><strong>DevOpsX</strong><small>CONTROL PLANE</small></div><div className="node node-aws"><Cloud size={18} /><span>AWS</span></div><div className="node node-azure"><Boxes size={18} /><span>AZURE</span></div><div className="node node-kube"><Container size={18} /><span>K8S</span></div><div className="node node-sec"><LockKeyhole size={16} /><span>SECURITY</span></div><div className="visual-line line-a" /><div className="visual-line line-b" /><div className="visual-line line-c" /><div className="visual-caption"><span className="status-dot" />SYSTEMS ONLINE <span>·</span> 24/7 OBSERVABILITY</div></div> }

function Hero() { return <section className="hero section-pad" id="top"><div className="hero-copy"><div className="eyebrow"><span /> DEVOPS & CLOUD CONSULTING</div><div className="availability"><span /> Accepting new projects for Q4 2026</div><h1>Cloud systems that help your business move <em>faster.</em></h1><p className="hero-lede">I help growing teams design, automate and secure the infrastructure behind reliable products, without adding unnecessary complexity.</p><div className="capabilities">{['Cloud architecture', 'Automation', 'DevSecOps', 'Reliability'].map((item) => <span key={item}><Check size={14} />{item}</span>)}</div><div className="hero-actions"><Button>Book a Project Call</Button><Button secondary href="#projects">See Selected Work</Button></div><div className="credibility"><span>Remote-first</span><i /><span>Practical advice</span><i /><span>Clear handover</span></div></div><InfrastructureVisual /></section> }
function Stats() { return <section className="stats"><div className="stats-inner">{stats.map((stat) => <div className="stat" key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div></section> }

function Services() { return <section className="section-pad section" id="services"><div className="section-heading"><div><div className="eyebrow">WHAT I DO</div><h2>Practical support for<br /><em>your next move.</em></h2></div><p>From production infrastructure to career-focused technical coaching, get clear guidance that helps you move forward with confidence.</p></div><div className="service-grid">{services.map((service, index) => { const Icon = serviceIcons[index]; return <article className="service-card" key={service.title}><div className="card-icon"><Icon size={21} /></div><h3>{service.title}</h3><p>{service.description}</p><a href="#contact">Discuss this <ArrowRight size={15} /></a></article> })}</div></section> }
function Solutions() { const items = [['01', 'Reduce deployment time', 'Automate CI/CD and eliminate repetitive deployment tasks.', Zap], ['02', 'Improve reliability', 'Build resilient Kubernetes and cloud infrastructure.', ShieldCheck], ['03', 'Strengthen security', 'Integrate security into the development and deployment lifecycle.', LockKeyhole], ['04', 'Reduce cloud cost', 'Identify waste and optimize infrastructure and workloads.', Sparkles]]; return <section className="section solutions-section" id="solutions"><div className="section-pad"><div className="section-heading"><div><div className="eyebrow">OUTCOMES, NOT OUTPUT</div><h2>Solutions built around<br /><em>your problems.</em></h2></div><p>Whether you are scaling fast or untangling legacy systems, the goal is always a calmer, more capable engineering team.</p></div><div className="solution-grid">{items.map(([number, title, text, Icon]) => <article className="solution-card" key={title}><span className="solution-number">{number}</span><Icon className="solution-icon" size={22} /><h3>{title}</h3><p>{text}</p><a href="#contact">Explore solution <ArrowRight size={15} /></a></article>)}</div><div className="workflow"><span>PLAN</span><i /><span>BUILD</span><i /><span>SECURE</span><i /><span>DEPLOY</span><i /><span>OBSERVE</span><i /><span>OPTIMIZE</span></div></div></section> }
function Technologies() { return <section className="section-pad section tech-section"><div className="section-heading"><div><div className="eyebrow">THE TOOLKIT</div><h2>Tools & technologies<br /><em>I work with.</em></h2></div></div><div className="tech-grid">{Object.entries(technologies).map(([category, tools]) => <div className="tech-group" key={category}><h3>{category}</h3><div>{tools.map((tool) => <span key={tool}>{tool}</span>)}</div></div>)}</div></section> }
function Projects() { return <section className="section projects-section" id="projects"><div className="section-pad"><div className="section-heading"><div><div className="eyebrow">REPRESENTATIVE WORK</div><h2>Real projects.<br /><em>Real impact.</em></h2></div><p>Case studies and representative work. Client details are kept confidential where appropriate.</p></div><div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.title}><div className={`project-visual project-${index + 1}`}><span>{project.label}</span><div className="project-lines" /></div><div className="project-body"><span className="project-type">{project.type}</span><h3>{project.title}</h3><p>{project.description}</p><div className="tag-row">{project.technologies.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div></div></section> }
function Process() { return <section className="section-pad section process-section"><div className="section-heading"><div><div className="eyebrow">A CLEAR PATH FORWARD</div><h2>How I <em>work.</em></h2></div><p>Good infrastructure work is collaborative, documented and designed to leave your team stronger than before.</p></div><div className="process-grid">{process.map((step, index) => <div className="process-step" key={step.number}><span>{step.number}</span>{index < process.length - 1 && <i /> }<h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section> }
function About() { return <section className="section about-section" id="about"><div className="section-pad about-grid"><div><div className="eyebrow">THE PERSON BEHIND THE PLATFORM</div><h2>Infrastructure should<br />feel <em>intentional.</em></h2></div><div className="about-copy"><p className="large-copy">DevOpsX is a focused DevOps, DevSecOps and cloud infrastructure consulting practice for teams who want to move quickly without making production fragile.</p><p>My work spans cloud infrastructure, Kubernetes, security automation, CI/CD, Infrastructure as Code and observability. The approach is practical: understand the constraints, simplify the system, and automate the path forward.</p><div className="about-tags">{['Production-focused engineering', 'Automation-first approach', 'Clear documentation', 'Remote collaboration'].map((tag) => <span key={tag}><Check size={14} />{tag}</span>)}</div></div></div></section> }
function Engagement() { return <section className="section-pad section engagement-section"><div className="section-heading"><div><div className="eyebrow">WAYS TO WORK TOGETHER</div><h2>Support that fits<br /><em>the moment.</em></h2></div></div><div className="engagement-grid">{[['Project based', 'Best for migrations, automation and infrastructure implementations.'], ['Hourly consulting', 'Best for troubleshooting, architecture reviews and technical guidance.'], ['Interview & assignment coaching', 'Best for mock interviews, technical preparation and feedback on take-home work.'], ['Monthly support', 'Best for companies requiring ongoing DevOps and cloud support.']].map(([title, text], index) => <article key={title} className={index === 1 ? 'engagement-card featured' : 'engagement-card'}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><a href="#contact">Discuss your needs <ArrowRight size={15} /></a></article>)}</div></section> }
function Blog() { return <section className="section blog-section" id="blog"><div className="section-pad"><div className="section-heading"><div><div className="eyebrow">FIELD NOTES</div><h2>Useful ideas for<br /><em>reliable systems.</em></h2></div><a className="text-link" href="#blog">View all notes <ArrowRight size={15} /></a></div><div className="blog-grid">{blogPosts.slice(0, 3).map((post) => <article className="blog-card" key={post.title}><div className="blog-art"><Terminal size={26} /><span>{post.category}</span></div><div><span className="post-meta">{post.readTime} · {post.date}</span><h3>{post.title}</h3><a href="#contact">Read article <ArrowRight size={15} /></a></div></article>)}</div></div></section> }
function Contact() { const [sent, setSent] = useState(false); const handleSubmit = (event) => { if (!CONTACT_FORM_ENDPOINT) { event.preventDefault(); const formData = new FormData(event.currentTarget); const subject = encodeURIComponent(`Project inquiry from ${formData.get('name')}`); const body = encodeURIComponent(`Name: ${formData.get('name')}\nEmail: ${formData.get('email')}\nCompany: ${formData.get('company') || 'Not provided'}\nProject type: ${formData.get('projectType') || 'Not provided'}\nBudget: ${formData.get('budget') || 'Not provided'}\n\n${formData.get('message')}`); window.location.href = `mailto:${CONTACT_EMAIL}?subject=${subject}&body=${body}`; setSent(true) } }; return <section className="contact-section" id="contact"><div className="section-pad contact-grid"><div className="contact-copy"><div className="eyebrow">START A CONVERSATION</div><h2>Make your next<br /><em>deployment</em><br />the easy one.</h2><p>Share what is slowing your team down. I’ll reply with a clear next step and an honest view of how I can help.</p><div className="contact-detail"><span>Prefer email?</span><a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></div><div className="contact-promise"><Check size={16} /> Reply within one business day</div></div><form className="contact-form" action={CONTACT_FORM_ENDPOINT || undefined} method="POST" onSubmit={handleSubmit}><div className="form-intro"><span>01</span><div><strong>Tell me about the work</strong><p>No pitch deck required. A few details are enough to start.</p></div></div><div className="form-row"><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@company.com" /></label></div><div className="form-row"><label>Company<input name="company" placeholder="Company name" /></label><label>Project type<select name="projectType" defaultValue=""><option value="" disabled>Select a focus area</option>{['DevOps Consulting', 'Cloud Migration', 'Kubernetes', 'Terraform / IaC', 'CI/CD', 'DevSecOps', 'Monitoring', 'Automation', 'Other'].map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Budget range<select name="budget" defaultValue=""><option value="" disabled>Choose a range</option>{['Under $500', '$500–$1,000', '$1,000–$5,000', '$5,000+', 'Not sure'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Message<textarea required name="message" rows="4" placeholder="What would you like to improve, launch or automate?" /></label>{sent && <p className="form-success">Your email draft is ready. Send it to complete your request.</p>}<button className="button form-button" type="submit">{CONTACT_FORM_ENDPOINT ? 'Book My Consultation' : 'Send Project Brief'} <ArrowRight size={16} /></button><small className="form-note">Typically replies within one business day. No obligation.</small></form></div></section> }
function Footer() { return <footer className="footer"><div className="footer-cta"><div><div className="eyebrow"><span /> READY WHEN YOU ARE</div><h2>Make the next<br /><em>move count.</em></h2></div><Button>Book a Project Call</Button></div><div className="footer-main"><div className="footer-brand"><Logo /><p>Build. Automate. Secure. Scale.</p><span className="footer-status"><i /> Available for remote consulting worldwide.</span></div><div className="footer-links"><div><span>Explore</span><a href="#services">Services</a><a href="#projects">Projects</a><a href="#about">About</a></div><div><span>Connect</span><a href={siteConfig.social.linkedin}>LinkedIn</a><a href={siteConfig.social.github}>GitHub</a><a href={siteConfig.social.youtube}>YouTube</a></div></div></div><div className="footer-bottom"><span>© 2026 DevOpsX. All rights reserved.</span><span>Independent DevOps & cloud consulting</span></div></footer> }

function AdLanding() { return <><Navbar /><main><section className="landing-hero section-pad"><div className="eyebrow"><span /> DEVOPS & CLOUD CONSULTING</div><h1>Hire a DevOps &<br /><em>Cloud Consultant.</em></h1><p>AWS, Azure, Kubernetes, Terraform, CI/CD and DevSecOps expertise for your next project.</p><Button>Book a Free Consultation</Button></section><Services /><Technologies /><Projects /><Engagement /><Contact /></main><Footer /></> }
function App() { const isLanding = window.location.pathname === '/devops-consulting' || window.location.hash === '#devops-consulting'; return isLanding ? <><AdLanding /><WhatsAppButton /></> : <><Navbar /><main><Hero /><Stats /><Services /><Solutions /><Technologies /><Projects /><Process /><About /><Engagement /><Blog /><Contact /></main><Footer /><WhatsAppButton /></> }

export default App
